[workspace]

members = [
    "egccri-core",
    "egccri-hub",
    "egccri-let",
    "library/module-sdk",
    "library/metamsg",
    "crates/egccri-connect-modbus",
    "crates/egccri-connect-mqtt",
    "crates/egccri-device-manager",
    "crates/egccri-device-model",
    "crates/egccri-storage-sqlite",
    "crates/egccri-compute/egccri-compute-core",
    "crates/egccri-compute/egccri-compute-uds",
    "crates/egccri-compute/egccri-compute-channel",
    "crates/egccri-compute/egccri-compute-scheduler",
    "crates/egccri-compute/egccri-compute-storage",
]

[profile.dev]
opt-level = 0

[profile.release]
panic = 'abort'
opt-level = 3