[workspace]

members = [
    "egccri-core",
    "egccri-hub",
    "egccri-let",
    "egccri-model",
    "library/module-sdk",
    "library/metamsg",
    "egccri-core/components/egccri-metadata",
    "egccri-core/components/egccri-streaming",
    "egccri-core/components/mqtt-server",
]

[profile.dev]
opt-level = 0

[profile.release]
panic = 'abort'
opt-level = 3