[workspace]

members = [
    "egccri-core",
    "egccri-hub",
    "egccri-let",
    "egccri-model",
    "library/module-sdk",
    "egccri-core/components/egccri-metadata",
    "egccri-core/components/egccri-streaming",
    "egccri-core/components/mqtt-server",
]