[package]
name = "egccri-cli"
version = "0.0.0"
authors = ["zifeng <zifeng.1024@gmail.com>"]
edition = "2021"

[lib]
doctest = false

[[bin]]
name = "egccri"
path = "src/bin/single_server.rs"
doc = false

[dependencies]
egccri-core = { path = "egccri-core" }
egccri-streaming = { path = "egccri-streaming" }
egccri-let = { path = "egccri-let" }
clap = "4.0.15"

[workspace]
members = [
    "egccri-core",
    "egccri-streaming",
    "egccri-hub",
    "egccri-let",
    "library/module-sdk",
    "library/metamsg",
    "library/micro-async-module",
    "crates/egccri-connect-modbus",
    "crates/egccri-connect-mqtt",
    "crates/egccri-device-manager",
    "crates/egccri-device-model",
    "crates/egccri-storage-sqlite",
    "crates/egccri-compute-core",
    "crates/egccri-compute-uds",
    "crates/egccri-compute-channel",
    "crates/egccri-compute-scheduler",
    "crates/egccri-compute-storage",
]

[profile.dev]
opt-level = 0

[profile.release]
panic = 'abort'
opt-level = 3