[package]
name = "egccri-compute-uds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "24.0.0"
datafusion = { version = "13.0.0", features = ["avro"] }
