[package]
name = "mqtt-server"
version = "0.0.0"
authors = ["zifeng <zifeng.1024@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
