[package]
name = "egccri-storage-sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egccri-device-model = { path = "../egccri-device-model" }
rusqlite = { version = "0.28.0", features = ["bundled"] }
thiserror = "1.0.37"

