[package]
name = "egccri-connect"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egccri-device-model = { path = "../crates/egccri-device-model" }
egccri-connect-modbus = { path = "../crates/egccri-connect-modbus", optional = true }
egccri-connect-mqtt = { path = "../crates/egccri-connect-mqtt", optional = true }
tokio = { version = "1", features = ["full"] }
anyhow = { workspace = true }
serde = "1.0.126"
serde_json = "1.0.67"
nng = "1.0.0"

[features]
default = ["mqtt"]
mqtt = ["egccri-connect-mqtt"]
opa-ua = []
modbus = ["egccri-connect-modbus"]
