[package]
name = "egccri-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egccri-api = { path = "../../crates/egccri-api" }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros"] }
parity-tokio-ipc = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
